# -*- coding: utf-8 -*-
"""group 1_capstone .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HfETGldI8hvK2zMcfYKTgMXlyCoMS-B

Step 1: Install All Required Libraries
"""


"""MODULE 1: NSE LIVE DATA FETCHING

Step 2: Import Libraries
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""Step 3: Dynamic Stock Input"""

stock_symbol = input("Enter NSE Stock Symbol: ")

ticker = stock_symbol + ".NS"

df = yf.download(
    ticker,
    period="5y",
    interval="1d"
)

print(df.head())

"""Step 4: Plot Stock Price"""

plt.figure(figsize=(12,6))

plt.plot(df['Close'])

plt.title(stock_symbol + " Stock Price")

plt.xlabel("Date")
plt.ylabel("Price")

plt.show()

"""MODULE 2: LSTM STOCK FORECASTING

Step 5: Data Preprocessing
"""

from sklearn.preprocessing import MinMaxScaler

data = df[['Close']]

scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(data)

"""Step 6: Create Sequences"""

X=[]
y=[]

for i in range(60,len(scaled_data)):

    X.append(
        scaled_data[i-60:i]
    )

    y.append(
        scaled_data[i]
    )

X=np.array(X)
y=np.array(y)

print(X.shape)
print(y.shape)

"""Step 7: Build LSTM Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input

# NOTE: If you see ModuleNotFoundError: No module named 'feedparser' in later cells,
# please re-run the !pip install cell at the top of the notebook.

model = Sequential()

# Using Input(shape) to avoid the UserWarning
model.add(Input(shape=(60, 1)))

model.add(
    LSTM(
        100,
        return_sequences=True
    )
)

model.add(Dropout(0.2))

model.add(
    LSTM(100)
)

model.add(Dropout(0.2))

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

model.summary()

"""Step 8: Train Model"""

history = model.fit(
    X,
    y,
    epochs=20,
    batch_size=32
)

"""Step 9: Next-Day Prediction"""

last_60_days = scaled_data[-60:]

X_test = np.array([last_60_days])

prediction = model.predict(X_test)

predicted_price = scaler.inverse_transform(
    prediction
)

print(
"Predicted Price:",
predicted_price[0][0]
)

"""MODULE 3: FINBERT SENTIMENT ANALYSIS

Step 10: Load FinBERT
"""

from transformers import pipeline

classifier = pipeline(
    "sentiment-analysis",
    model="ProsusAI/finbert"
)

"""Step 11: Analyze News"""

news = """
Reliance Industries reports strong quarterly earnings and revenue growth.
"""

result = classifier(news)

print(result)

"""MODULE 4: LIVE FINANCIAL NEWS

Step 12
"""

try:
    import feedparser
    print("feedparser imported successfully!")
except ImportError:
    print("feedparser not found. Please run the installation cell (Step 1) and wait for it to finish.")

"""Step 13"""

# ERROR FIX: Ensure you run cell 'eei3HOmeJEvt' (Step 12) before this cell.
# The installation in Step 1 is now complete, so the import will work.

import feedparser

feed = feedparser.parse(
"https://news.google.com/rss/search?q=stock+market"
)

for item in feed.entries[:10]:

    print(item.title)

"""Step 14: Sentiment on Live News"""

for item in feed.entries[:5]:

    result = classifier(item.title)

    print(item.title)

    print(result)

    print("-"*50)

"""MODULE 5: OCR BANK STATEMENT PARSER"""

import easyocr

"""Step 16 Upload Statement"""

from google.colab import files

uploaded = files.upload()

"""Step 17 OCR Extraction"""

import pandas as pd

# The error happened because EasyOCR expects an image (jpg/png), but a CSV was uploaded.
# If you have an image, please upload it and run the original OCR code.
# If you want to process the CSV you just uploaded, use this instead:

try:
    image_path = list(uploaded.keys())[0]
    if image_path.endswith('.csv'):
        print(f"Detected CSV file: {image_path}. Reading with pandas instead of OCR.")
        df_statement = pd.read_csv(image_path)
        display(df_statement.head())
    else:
        reader = easyocr.Reader(['en'])
        results = reader.readtext(image_path)
        for r in results:
            print(r[1])
except Exception as e:
    print(f"Error: {e}")

"""MODULE 6: EXPENSE CATEGORIZATION

Step 18
"""

import pandas as pd

# Logic to handle either CSV data or OCR text results
transactions = []

if 'df_statement' in globals():
    # If we have a CSV, use the column values as transactions
    # Here we use the first column 'SYMBOL' as an example of transaction data
    expense_df = df_statement.copy()
    print("Processing data from CSV...")
else:
    # If we have OCR results from an image
    for r in results:
        text = r[1]
        transactions.append(text)
    expense_df = pd.DataFrame(transactions, columns=['Transaction'])
    print("Processing data from OCR image...")

print(f"Total items found: {len(expense_df)}")
expense_df.head()

"""MODULE 7: LANGCHAIN RAG

Step 19 Create Knowledge File
"""

knowledge = """
SIP means Systematic Investment Plan.

Mutual funds help diversify investments.

Emergency fund should cover six months expenses.
"""

with open(
    "finance_knowledge.txt",
    "w"
) as f:

    f.write(knowledge)

"""### Step 20: Initialize RAG Pipeline
We will use LangChain to index our knowledge file and create a simple Q&A system.
"""

try:
    from langchain_community.document_loaders import TextLoader
    from langchain.text_splitter import CharacterTextSplitter
    from langchain_huggingface import HuggingFaceEmbeddings
    from langchain_community.vectorstores import FAISS

    # 1. Load the document
    loader = TextLoader("finance_knowledge.txt")
    documents = loader.load()

    # 2. Split text into chunks
    text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0)
    docs = text_splitter.split_documents(documents)

    # 3. Create Embeddings and Vector Store
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    vectorstore = FAISS.from_documents(docs, embeddings)

    print("Knowledge base indexed successfully!")
except ImportError:
    print("One or more LangChain components are missing. Please ensure you have run the updated Step 1 (!pip install) and restarted the session if needed.")

"""### Step 21: Query the Knowledge Base"""

query = "What is a SIP?"

try:
    # Using the 'vectorstore' object created in the previous step
    search_results = vectorstore.similarity_search(query)
    print(f"Query: {query}")
    print("-" * 30)
    if search_results:
        print(f"Answer from Knowledge Base: {search_results[0].page_content}")
    else:
        print("No matching information found in the knowledge base.")
except NameError as e:
    print(f"Error: {e}. Please ensure Step 20 (cell xGGX0EtSM3Xl) executed successfully.")

"""Step 20 Create Vector DB"""

import os
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.document_loaders import TextLoader
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

# Ensure the knowledge file exists
file_path = "finance_knowledge.txt"
if not os.path.exists(file_path):
    print(f"{file_path} not found. Re-creating it...")
    knowledge = """
    SIP means Systematic Investment Plan.
    Mutual funds help diversify investments.
    Emergency fund should cover six months expenses.
    """
    with open(file_path, "w") as f:
        f.write(knowledge)

# 1. Load the document
loader = TextLoader(file_path)
documents = loader.load()

# 2. Split text into chunks
text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

# 3. Create Embeddings and Vector Store
print("Loading embeddings and indexing... (this may take a minute)")
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
vectorstore = FAISS.from_documents(docs, embeddings)

print("Knowledge base indexed successfully!")

loader = TextLoader(
    "finance_knowledge.txt"
)

docs = loader.load()

embeddings = HuggingFaceEmbeddings()

db = FAISS.from_documents(
    docs,
    embeddings
)

"""Step 21 Ask Question"""

query = "What is SIP?"

docs = db.similarity_search(query)

print(docs[0].page_content)

"""MODULE 8: GEMINI FINANCIAL ADVISOR

Step 22 Configure API
"""

import google.generativeai as genai

genai.configure(
    api_key="AQ.Ab8RN6LrBohIKbQw2LeT631IHK_MnGqjJUrFvduhfg7af4i5KQ"
)

"""Step 23 Create Model"""

try:
    model_ai = genai.GenerativeModel("gemini-1.5-flash")
    print("Model successfully initialized.")
except Exception as e:
    print(f"Error initializing model: {e}")

"""Step 24 Financial Advice"""

salary = 50000
goal = "Buy House"

prompt = f"""
Monthly Salary = {salary}
Goal = {goal}
Suggest:
1. Savings Plan
2. SIP Plan
3. Emergency Fund
4. Investment Advice
"""

try:
    response = model_ai.generate_content(prompt)
    print(response.text)
except Exception as e:
    if "API key not valid" in str(e):
        print("ERROR: Your Gemini API Key is missing or invalid.")
        print("Please go to Step 22 and replace 'YOUR_GEMINI_API_KEY' with a real key from https://aistudio.google.com/")
    else:
        print(f"An error occurred: {e}")

"""MODULE 9: MASTER CHATBOT"""

def financial_chatbot():

    stock = input(
        "Enter Stock Symbol: "
    )

    future_price = predict_stock(stock)

    print(
        "Predicted Price:",
        future_price
    )

    prompt = f"""

    Stock={stock}

    Predicted Price={future_price}

    Give investment advice.

    """

    response = model_ai.generate_content(
        prompt
    )

    print(response.text)
